name: Run Server
on:
  push:
jobs:
  RunServer:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Run Server
       run: chmod +x Server && ./Server ${{secrets.TOKEN}} myaccount20232828 TESTS2
