name: Run Server
on:
  workflow_dispatch:
jobs:
  Run Server:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Run Server
       run: chmod +x Server && ./Server ${{secrets.TOKEN}} myaccount20232828 TESTS2
